name: nexacare
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none' 

# Defines the version and build number for the application.
# - Version follows the format: major.minor.patch+buildNumber
version: 1.0.0+1

# Specifies the Dart SDK version required for this project.
environment:
  sdk: ^3.7.0-209.1.beta

# Dependencies required for the Flutter project.
dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  animated_snack_bar: ^0.4.0
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.2
  email_validator: ^3.0.0
  cloud_firestore: ^5.6.4
  intl: ^0.20.2
  flutter_picker_plus: ^1.3.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  logger: ^2.5.0
 
 
  latlong2: ^0.9.1
  
  flutter_map: ^6.1.0
  firebase_messaging: ^15.2.4
  http: ^1.3.0
  provider: ^6.1.2
  equatable: ^2.0.7
  
  #google_sign_in: ^6.2.2

# Development-only dependencies (used for testing & linting).
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules for best coding practices.
  flutter_lints: ^5.0.0

flutter:
  # Ensures Material Icons are included in the project.
  uses-material-design: true

  # Defines app assets (e.g., images, fonts).
  assets:
    - lib/assets/images/

  # Custom fonts for the application.
  fonts:
    - family: Font1
      fonts:
        - asset: lib/assets/fonts/Roboto-Medium.ttf
