// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtJ0sse3iUW3odV1iFk66qrj9ubV2u7nc',
    appId: '1:899597567245:web:61730b59b974230853dc44',
    messagingSenderId: '899597567245',
    projectId: 'nexacare-d797f',
    authDomain: 'nexacare-d797f.firebaseapp.com',
    storageBucket: 'nexacare-d797f.firebasestorage.app',
    measurementId: 'G-F7R773HRFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZXImq2LnYbo_x_D_sNXb7ZX-zlEuh2vg',
    appId: '1:899597567245:android:60d0931709c6f93553dc44',
    messagingSenderId: '899597567245',
    projectId: 'nexacare-d797f',
    storageBucket: 'nexacare-d797f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPlsJPNwlC5liy-wYFclw9tnlxTFkqTk0',
    appId: '1:899597567245:ios:1ee2355e7b2e7e9053dc44',
    messagingSenderId: '899597567245',
    projectId: 'nexacare-d797f',
    storageBucket: 'nexacare-d797f.firebasestorage.app',
    iosBundleId: 'com.example.nexacare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPlsJPNwlC5liy-wYFclw9tnlxTFkqTk0',
    appId: '1:899597567245:ios:1ee2355e7b2e7e9053dc44',
    messagingSenderId: '899597567245',
    projectId: 'nexacare-d797f',
    storageBucket: 'nexacare-d797f.firebasestorage.app',
    iosBundleId: 'com.example.nexacare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtJ0sse3iUW3odV1iFk66qrj9ubV2u7nc',
    appId: '1:899597567245:web:4239a9a2fa0f3c7a53dc44',
    messagingSenderId: '899597567245',
    projectId: 'nexacare-d797f',
    authDomain: 'nexacare-d797f.firebaseapp.com',
    storageBucket: 'nexacare-d797f.firebasestorage.app',
    measurementId: 'G-PRGWGGTXFL',
  );
}
